image: python:3.8

before script:
 -pip install -r requirements
 
 pages:
    script:
      - mkdocs build
      - mv site public
    artifacts:
      paths:
        -public
    only:
        - master