site_name: ACESSOGOV - MERCADO PRIVADO

nav:
  - Home: index.md
  - Legislação e Conceitos:
      - Introdução: LEGISLACAO_E_CONCEITOS/vertopal.com_introdução.md
      - Contexto: LEGISLACAO_E_CONCEITOS/vertopal.com_contexto.md
      - Catalogo de Confiabilidades: LEGISLACAO_E_CONCEITOS/vertopal.com_catalogoconfiabilidades.md
      - Escopo de atributos: LEGISLACAO_E_CONCEITOS/vertopal.com_escopoatributos.md
  - Informações Técnicas para Integração:
      - Client Manager: INFORMACOES_TECNICAS_PARA_INTEGRACAO/vertopal.com_clientmanager.md
      - Chave Pgp: INFORMACOES_TECNICAS_PARA_INTEGRACAO/vertopal.com_chavepgp.md
      - Solicitar configuração: INFORMACOES_TECNICAS_PARA_INTEGRACAO/vertopal.com_solicitarconfiguracao.md
      - Configurar a integração: INFORMACOES_TECNICAS_PARA_INTEGRACAO/vertopal.com_iniciarintegracao.md
      - Exemplo de implementação: INFORMACOES_TECNICAS_PARA_INTEGRACAO/vertopal.com_exemplointegracao.md
      - Execução do exemplo de implementação: INFORMACOES_TECNICAS_PARA_INTEGRACAO/vertopal.com_execucaoexemplo.md
  - Dúvidas Frequentes:
      - Validação de dados pessoais: LEGISLACAO_E_CONCEITOS/DUVIDAS_FREQUENTES/validacao-dados-pessoais.md
      - Validação de dados previdenciários: LEGISLACAO_E_CONCEITOS/DUVIDAS_FREQUENTES/validacao-dados-previdenciarios.md
      - Atribuição de Selo Balcão Presencial: LEGISLACAO_E_CONCEITOS/DUVIDAS_FREQUENTES/aquisicao-selo-balcao-presencial-inss.md
      - Atribuição de Selo Internet Banking: LEGISLACAO_E_CONCEITOS/DUVIDAS_FREQUENTES/aquisicao-selo-internet-banking.md
      - Atribuição de Selo Cadastro Básico com Validação em Base de Dados de Servidores Públicos da União: LEGISLACAO_E_CONCEITOS/DUVIDAS_FREQUENTES/atribuicao-selo-cadastro-basico-servidores.md
      - Atribuição de Selo Validação Facial: LEGISLACAO_E_CONCEITOS/DUVIDAS_FREQUENTES/atribuicao-selo-validacao-facial.md
      - Atribuição de Selo de Cada Banco Credenciado: LEGISLACAO_E_CONCEITOS/DUVIDAS_FREQUENTES/atribuicao-selo-banco-credenciado.md



theme: 
 name: material
 palette:
   - scheme: default
     primary: blue
     toggle:
      icon: material/weather-night
      name: Modo noturno
   - scheme: slate
     primary: deep blue
     toggle:
      icon: material/weather-sunny
      name: Modo claro
markdown_extensions:
 - pymdownx.emoji
 - pymdownx.tasklist
 - pymdownx.mark
 - pymdownx.tilde
 - pymdownx.highlight
