site_name: ACESSOGOV - MERCADO PRIVADO

nav:
  - Home: index.md
  - Legislação e Conceitos:
      - Introdução: LEGISLACAO_E_CONCEITOS/vertopal.com_introdução.md
      - Contexto: LEGISLACAO_E_CONCEITOS/vertopal.com_contexto.md
      - Catalogo de Confiabilidades: LEGISLACAO_E_CONCEITOS/vertopal.com_catalogoconfiabilidades.md
      - Escopo de atributos: LEGISLACAO_E_CONCEITOS/vertopal.com_escopoatributos.md
  - Informações Técnicas para Integração:
      - Chave Pgp: INFORMACOES_TECNICAS_PARA_INTEGRACAO/vertopal.com_chavepgp.md
      - Solicitar configuração: INFORMACOES_TECNICAS_PARA_INTEGRACAO/vertopal.com_solicitarconfiguracao.md
      - Configurar a integração: INFORMACOES_TECNICAS_PARA_INTEGRACAO/vertopal.com_iniciarintegracao.md
      - Exemplo de implementação: INFORMACOES_TECNICAS_PARA_INTEGRACAO/vertopal.com_exemplointegracao.md
      - Execução do exemplo de implementação: INFORMACOES_TECNICAS_PARA_INTEGRACAO/vertopal.com_execucaoexemplo.md

theme: 
 name: material
 palette:
   - scheme: default
     primary: blue
     toggle:
      icon: material/weather-night
      name: Modo noturno
   - scheme: slate
     primary: deep blue
     toggle:
      icon: material/weather-sunny
      name: Modo claro
markdown_extensions:
 - pymdownx.emoji
 - pymdownx.tasklist
 - pymdownx.mark
 - pymdownx.tilde
 - pymdownx.highlight
